function deshabilitarControlYGrabacion( visorDelProceso, tipoSetDeControl)
    handles = guihandles(visorDelProceso);
    if strcmp(tipoSetDeControl, 'Reproduccion')
        controles = [handles.txtSetPoint, handles.slSetPoint, ...
                handles.txtBias, handles.slBias, ...
                handles.txtKp, handles.slKp, ...
                handles.txtKi, handles.slKi, ...
                handles.txtKd, handles.slKd, ...
                handles.txtManual, handles.slManual, handles.Grabacion, handles.GuardarConfigDeControl];
        set(controles, 'Enable', 'off');
    else
        controles = [handles.FinalizarGrabacion];
        set(controles, 'Enable', 'off');
    end